name: filter_price_product
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.1.1
  logger: 1.3.0
  dio: ^4.0.4
  cached_network_image: ^3.2.3
  skeletons: 0.0.3
  intl: ^0.17.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get_test: ^4.0.1
  mocktail: ^0.3.0

flutter: 
  uses-material-design: true

